"""Curated word/clue banks for the daily word search and crossword.

Deliberately not tied to current events: these are evergreen, whimsical
themes so the games hold up regardless of the news cycle. Words are
uppercase, letters only (no spaces or hyphens) so they place cleanly on a
grid. Clues are only used by the crossword; the word search just needs the
word list.

Add a new theme by adding a new (word, clue) list below. Keep clues short
(under ~45 chars looks best in the sidebar clue list) and avoid duplicate
words within a theme.
"""

THEMES = {
    "Ocean Life": [
        ("WHALE", "Largest animal on Earth"),
        ("CORAL", "Reef-building sea organism"),
        ("OCTOPUS", "Eight-armed cephalopod"),
        ("STARFISH", "Sea animal shaped like a star"),
        ("SHARK", "Cartilaginous ocean predator"),
        ("DOLPHIN", "Playful, clever marine mammal"),
        ("PLANKTON", "Tiny drifting sea organisms"),
        ("TIDE", "Daily rise and fall of the sea"),
        ("KELP", "Large brown seaweed"),
        ("ANCHOR", "Keeps a ship from drifting"),
        ("LAGOON", "Shallow water near a coast"),
        ("CRAB", "Walks sideways, has claws"),
        ("PEARL", "Gem formed inside an oyster"),
        ("REEF", "Coral ridge near the surface"),
        ("HARBOR", "Sheltered place for ships"),
        ("SEAHORSE", "Fish with a horse-shaped head"),
        ("JELLYFISH", "Gelatinous, stings"),
        ("TSUNAMI", "Huge wave from a quake"),
        ("LOBSTER", "Clawed crustacean, turns red cooked"),
        ("CURRENT", "Steady flow of moving water"),
    ],
    "Space Explorer": [
        ("ROCKET", "Vehicle that launches into orbit"),
        ("COMET", "Icy body with a glowing tail"),
        ("GALAXY", "Huge collection of star systems"),
        ("METEOR", "Shooting star burning in the sky"),
        ("ORBIT", "Path a planet takes around a star"),
        ("NEBULA", "Cloud of gas and dust in space"),
        ("ASTEROID", "Rocky object orbiting the sun"),
        ("TELESCOPE", "Tool for viewing distant stars"),
        ("ASTRONAUT", "Person trained to travel in space"),
        ("SATELLITE", "Object orbiting a planet"),
        ("GRAVITY", "Force that pulls objects together"),
        ("ECLIPSE", "One body blocks light from another"),
        ("MOON", "Earth's only natural satellite"),
        ("SATURN", "Planet known for its rings"),
        ("MARS", "The red planet"),
        ("STARLIGHT", "Light that traveled years to reach us"),
        ("CAPSULE", "Crew compartment of a spacecraft"),
        ("LAUNCHPAD", "Where a rocket lifts off"),
        ("COSMOS", "The universe as an orderly whole"),
        ("CONSTELLATION", "Named pattern of stars"),
    ],
    "Kitchen Table": [
        ("SKILLET", "Flat-bottomed pan for frying"),
        ("WHISK", "Tool for beating eggs or batter"),
        ("SIMMER", "Cook gently just below boiling"),
        ("PANTRY", "Small room for storing food"),
        ("RECIPE", "Instructions for making a dish"),
        ("SPATULA", "Flat tool for flipping food"),
        ("KETTLE", "Container for boiling water"),
        ("GARLIC", "Pungent bulb used in cooking"),
        ("CINNAMON", "Warm, sweet spice from bark"),
        ("CASSEROLE", "Baked dish made in one pan"),
        ("BLENDER", "Appliance that purees or mixes"),
        ("APPETIZER", "Small dish served before the meal"),
        ("MARINATE", "Soak food in seasoned liquid"),
        ("COLANDER", "Bowl with holes for draining"),
        ("DESSERT", "Sweet course at the end of a meal"),
        ("OMELET", "Folded dish made of beaten eggs"),
        ("PRETZEL", "Salty, twisted baked snack"),
        ("VINEGAR", "Sour liquid used in dressings"),
        ("TEASPOON", "Small unit for measuring spice"),
        ("BAKERY", "Shop that sells fresh bread"),
    ],
    "Backyard Camping": [
        ("TENT", "Portable shelter for sleeping outside"),
        ("LANTERN", "Portable light for a campsite"),
        ("CAMPFIRE", "Fire built for warmth outdoors"),
        ("MARSHMALLOW", "Sweet treat roasted on a stick"),
        ("SLEEPBAG", "Padded sack for outdoor sleeping"),
        ("COMPASS", "Tool that points north"),
        ("FLASHLIGHT", "Handheld electric light"),
        ("HAMMOCK", "Hanging bed for lounging outside"),
        ("TRAIL", "Path used for hiking"),
        ("BACKPACK", "Bag carried on the shoulders"),
        ("FIREFLY", "Bug that glows at night"),
        ("BINOCULARS", "Tool for seeing far away"),
        ("CANOE", "Narrow boat paddled by hand"),
        ("BONFIRE", "Large outdoor fire"),
        ("STARGAZING", "Looking up at the night sky"),
        ("COOLER", "Box that keeps food and drinks cold"),
        ("RIVERBANK", "Land along the edge of a river"),
        ("WHISTLE", "Small tool that makes a sharp sound"),
        ("PINECONE", "Woody seed case from a conifer"),
        ("MOSQUITO", "Small biting insect"),
    ],
    "Movie Night": [
        ("POPCORN", "Snack popped from kernels"),
        ("SEQUEL", "Follow-up to an earlier film"),
        ("DIRECTOR", "Person who oversees a film's making"),
        ("SUBTITLE", "Translated text at the bottom of a screen"),
        ("PREMIERE", "A film's first public showing"),
        ("SOUNDTRACK", "Music that plays through a film"),
        ("CAMEO", "Brief appearance by a known actor"),
        ("SCREENPLAY", "Written script for a film"),
        ("BLOCKBUSTER", "Hugely successful film"),
        ("ANIMATION", "Film made from drawn or CGI frames"),
        ("TRAILER", "Short preview of a coming film"),
        ("PLOT", "The story of a film"),
        ("VILLAIN", "The bad guy in the story"),
        ("COSTUME", "Clothing worn by a character"),
        ("STUDIO", "Company that produces films"),
        ("REWIND", "Go back to an earlier scene"),
        ("MATINEE", "Afternoon showing of a film"),
        ("CREDITS", "Names listed at a film's end"),
        ("SCENE", "A single continuous piece of action"),
        ("BOXOFFICE", "Measure of a film's ticket sales"),
    ],
    "Road Trip": [
        ("HIGHWAY", "Major road between cities"),
        ("SUITCASE", "Case for packing clothes"),
        ("MAP", "Guide showing roads and routes"),
        ("DINER", "Casual roadside restaurant"),
        ("GASSTOP", "Quick stop to refuel"),
        ("BILLBOARD", "Large roadside advertisement"),
        ("PASSENGER", "Rider who isn't driving"),
        ("DETOUR", "Route that avoids the usual path"),
        ("LICENSE", "Permit required to drive"),
        ("TRUNK", "Storage space at the back of a car"),
        ("SPEEDOMETER", "Gauge showing how fast you're going"),
        ("MOTEL", "Roadside lodging for travelers"),
        ("TOLLBOOTH", "Stop for paying to use a road"),
        ("SOUVENIR", "Item kept to remember a trip"),
        ("CARAVAN", "Group of vehicles traveling together"),
        ("MILEAGE", "Distance a vehicle has traveled"),
        ("PITSTOP", "Short break during a long drive"),
        ("SUNROOF", "Panel that opens in a car's roof"),
        ("HORIZON", "Line where the sky meets the land"),
        ("GLOVEBOX", "Small storage compartment in a car"),
    ],
    "In the Garden": [
        ("TROWEL", "Small hand tool for digging"),
        ("SPROUT", "Young plant just emerging"),
        ("COMPOST", "Rotted matter that enriches soil"),
        ("SEEDLING", "A very young plant"),
        ("WATERING", "Giving plants a drink"),
        ("TRELLIS", "Frame for climbing plants"),
        ("PETALS", "Colorful parts of a flower"),
        ("WEEDING", "Pulling unwanted plants"),
        ("BLOSSOM", "A flower in bloom"),
        ("SHOVEL", "Tool for moving soil"),
        ("HARVEST", "Gathering ripe crops"),
        ("GREENHOUSE", "Glass house for growing plants"),
        ("MULCH", "Cover that protects soil"),
        ("PRUNE", "Trim back a plant"),
        ("FERTILIZER", "Feed that helps plants grow"),
        ("WHEELBARROW", "One-wheeled garden cart"),
        ("SUNFLOWER", "Tall flower that follows the sun"),
        ("BUMBLEBEE", "Fuzzy garden pollinator"),
        ("SPRINKLER", "Device that sprays water"),
        ("TOMATO", "Red fruit grown on a vine"),
    ],
    "Weather Watch": [
        ("THUNDER", "Loud rumble after lightning"),
        ("DRIZZLE", "Light, fine rain"),
        ("BLIZZARD", "Fierce snowstorm"),
        ("RAINBOW", "Arc of color after rain"),
        ("HUMIDITY", "Amount of moisture in the air"),
        ("FORECAST", "Prediction of coming weather"),
        ("TORNADO", "Spinning funnel of wind"),
        ("OVERCAST", "Fully clouded sky"),
        ("HAILSTONE", "Ball of ice that falls"),
        ("BAROMETER", "Gauge of air pressure"),
        ("MONSOON", "Season of heavy rains"),
        ("SUNSHINE", "Bright light from the sun"),
        ("FLURRIES", "Light, brief snow"),
        ("LIGHTNING", "Flash in a storm"),
        ("BREEZE", "Gentle wind"),
        ("FROST", "Thin ice on cold surfaces"),
        ("CYCLONE", "Large rotating storm"),
        ("DROUGHT", "Long spell without rain"),
        ("CLOUDY", "Full of clouds"),
        ("WINDCHILL", "How cold the wind makes it feel"),
    ],
    "Farm Life": [
        ("TRACTOR", "Machine that pulls farm gear"),
        ("BARNYARD", "Area around a barn"),
        ("ROOSTER", "Male chicken that crows"),
        ("HAYSTACK", "Pile of dried grass"),
        ("PASTURE", "Field where animals graze"),
        ("SCARECROW", "Figure that frightens birds"),
        ("HARVEST", "Gathering of ripe crops"),
        ("PIGLET", "A young pig"),
        ("SILO", "Tall tower storing grain"),
        ("PLOW", "Tool that turns the soil"),
        ("CHICKEN", "Common farmyard bird"),
        ("MEADOW", "Grassy open field"),
        ("STABLE", "Building that houses horses"),
        ("BUSHEL", "Unit for measuring grain"),
        ("ORCHARD", "Field of fruit trees"),
        ("CATTLE", "Herd of cows"),
        ("SHEARING", "Cutting wool from sheep"),
        ("FURROW", "Groove cut by a plow"),
        ("GRANARY", "Storehouse for grain"),
        ("MILKING", "Drawing milk from a cow"),
    ],
    "Winter Wonderland": [
        ("SNOWFLAKE", "Delicate crystal of ice"),
        ("MITTENS", "Warm coverings for hands"),
        ("SLEDDING", "Sliding downhill on snow"),
        ("ICICLE", "Hanging spike of ice"),
        ("SNOWMAN", "Figure built from snow"),
        ("FROSTBITE", "Cold injury to skin"),
        ("SHIVER", "Shake from the cold"),
        ("TOBOGGAN", "Long flat sled"),
        ("BLIZZARD", "Fierce snowstorm"),
        ("FIREPLACE", "Hearth that warms a room"),
        ("SNOWBALL", "Packed sphere of snow"),
        ("EARMUFFS", "Warm covers for the ears"),
        ("ICESKATE", "Blade worn for gliding on ice"),
        ("SNOWDRIFT", "Bank of wind-blown snow"),
        ("COCOA", "Warm chocolate drink"),
        ("FLURRY", "Brief fall of snow"),
        ("SNOWSHOE", "Wide frame for walking on snow"),
        ("SLUSH", "Half-melted snow"),
        ("SCARF", "Cloth worn around the neck"),
        ("SNOWPLOW", "Truck that clears roads"),
    ],
    "At the Beach": [
        ("SEASHELL", "Hard case left by a sea creature"),
        ("SANDCASTLE", "Sculpture built from sand"),
        ("SUNSCREEN", "Lotion that blocks the sun"),
        ("SURFBOARD", "Board for riding waves"),
        ("SEAGULL", "Bird that circles the shore"),
        ("BOARDWALK", "Wooden path by the sea"),
        ("UMBRELLA", "Shade from the sun"),
        ("SNORKEL", "Tube for breathing underwater"),
        ("DRIFTWOOD", "Wood washed up on shore"),
        ("LOWTIDE", "When the sea pulls back"),
        ("FLIPFLOP", "Simple open sandal"),
        ("SEAWEED", "Plant that drifts in the surf"),
        ("SANDBAR", "Ridge of sand offshore"),
        ("BEACHBALL", "Inflatable ball for play"),
        ("LIFEGUARD", "Watcher who keeps swimmers safe"),
        ("SEASHORE", "Where land meets the sea"),
        ("COOLER", "Box that keeps drinks cold"),
        ("PADDLE", "Tool for moving a small boat"),
        ("SUNTAN", "Darkened skin from the sun"),
        ("HORIZON", "Line where sea meets sky"),
    ],
    "Jungle Safari": [
        ("ELEPHANT", "Huge animal with a trunk"),
        ("MONKEY", "Tree-swinging primate"),
        ("PARROT", "Colorful talking bird"),
        ("LEOPARD", "Spotted big cat"),
        ("GORILLA", "Largest of the apes"),
        ("CROCODILE", "Toothy reptile in rivers"),
        ("TIGER", "Striped orange big cat"),
        ("PYTHON", "Large squeezing snake"),
        ("TOUCAN", "Bird with a huge bill"),
        ("VINES", "Ropes of jungle greenery"),
        ("CANOPY", "Leafy roof of the forest"),
        ("JAGUAR", "Powerful spotted cat"),
        ("MACHETE", "Blade for clearing brush"),
        ("QUICKSAND", "Sinking wet sand"),
        ("ANTEATER", "Animal that laps up ants"),
        ("HABITAT", "An animal's natural home"),
        ("EXPLORER", "One who travels wild places"),
        ("RIVERBED", "Bottom of a river"),
        ("BINOCULARS", "Tool for seeing far off"),
        ("PREDATOR", "Animal that hunts others"),
    ],
    "Musical Instruments": [
        ("TRUMPET", "Brass horn with valves"),
        ("VIOLIN", "Small stringed instrument"),
        ("PIANO", "Keyboard with hammered strings"),
        ("GUITAR", "Six-stringed instrument"),
        ("FLUTE", "Slender woodwind held sideways"),
        ("DRUMS", "Struck for rhythm"),
        ("SAXOPHONE", "Curved brass reed instrument"),
        ("HARP", "Large plucked stringed frame"),
        ("CELLO", "Large low-pitched string instrument"),
        ("CLARINET", "Woodwind with a single reed"),
        ("TROMBONE", "Brass horn with a slide"),
        ("BANJO", "Twangy round-bodied instrument"),
        ("TAMBOURINE", "Small drum with jingles"),
        ("KEYBOARD", "Electronic set of keys"),
        ("TRIANGLE", "Struck metal percussion"),
        ("UKULELE", "Small four-stringed instrument"),
        ("BAGPIPES", "Windbag instrument with pipes"),
        ("MARIMBA", "Wooden bars struck with mallets"),
        ("HARMONICA", "Small mouth-blown reed instrument"),
        ("ACCORDION", "Bellows-driven keyboard"),
    ],
    "The Human Body": [
        ("SKELETON", "Framework of bones"),
        ("MUSCLE", "Tissue that produces motion"),
        ("STOMACH", "Organ that digests food"),
        ("KIDNEY", "Organ that filters blood"),
        ("ELBOW", "Joint in the middle of the arm"),
        ("ARTERY", "Vessel carrying blood from the heart"),
        ("LUNGS", "Organs used for breathing"),
        ("SPINE", "Column of the backbone"),
        ("TONGUE", "Muscle used for taste"),
        ("KNUCKLE", "Joint of a finger"),
        ("EYEBROW", "Hair above the eye"),
        ("ANKLE", "Joint above the foot"),
        ("NERVES", "Fibers that carry signals"),
        ("SHOULDER", "Joint where arm meets body"),
        ("EARDRUM", "Membrane that senses sound"),
        ("KNEECAP", "Bone at the front of the knee"),
        ("EYELASH", "Hair on the edge of the eyelid"),
        ("FOREARM", "Arm between wrist and elbow"),
        ("HEARTBEAT", "Steady pulse of the heart"),
        ("NOSTRIL", "Opening of the nose"),
    ],
    "World Landmarks": [
        ("PYRAMID", "Ancient Egyptian monument"),
        ("COLOSSEUM", "Ancient Roman arena"),
        ("EIFFEL", "Famous iron tower in Paris"),
        ("STONEHENGE", "Ring of ancient standing stones"),
        ("PARTHENON", "Temple atop the Acropolis"),
        ("TAJMAHAL", "White marble tomb in India"),
        ("KREMLIN", "Fortress at the heart of Moscow"),
        ("ACROPOLIS", "Ancient hilltop citadel"),
        ("SPHINX", "Lion-bodied statue in Egypt"),
        ("BIGBEN", "Famous London clock tower"),
        ("LOUVRE", "Paris museum with the Mona Lisa"),
        ("VATICAN", "Tiny city within Rome"),
        ("ALHAMBRA", "Moorish palace in Spain"),
        ("PANTHEON", "Domed temple in Rome"),
        ("OPERAHOUSE", "Sail-shaped Sydney landmark"),
        ("GATEWAY", "St. Louis arch"),
        ("FORBIDDEN", "Vast palace city in Beijing"),
        ("PETRA", "Rose-red city carved in rock"),
        ("NIAGARA", "Famous set of waterfalls"),
        ("MACHUPICCHU", "Inca city in the Andes"),
    ],
    "Breakfast Foods": [
        ("PANCAKE", "Flat cake cooked on a griddle"),
        ("OATMEAL", "Warm cooked cereal"),
        ("OMELET", "Folded dish of beaten eggs"),
        ("WAFFLE", "Grid-patterned breakfast cake"),
        ("BACON", "Crispy strips of cured pork"),
        ("GRANOLA", "Toasted oats and nuts"),
        ("BAGEL", "Ring-shaped bread roll"),
        ("SAUSAGE", "Seasoned ground meat link"),
        ("YOGURT", "Cultured, creamy dairy food"),
        ("MUFFIN", "Small domed baked cake"),
        ("TOAST", "Browned slice of bread"),
        ("CROISSANT", "Flaky, buttery pastry"),
        ("SCRAMBLE", "Eggs stirred as they cook"),
        ("SYRUP", "Sweet topping for pancakes"),
        ("CEREAL", "Grain food eaten with milk"),
        ("BISCUIT", "Soft, flaky quick bread"),
        ("ESPRESSO", "Strong concentrated coffee"),
        ("HASHBROWN", "Fried shredded potatoes"),
        ("JELLY", "Sweet fruit spread"),
        ("PORRIDGE", "Boiled grain breakfast"),
    ],
    "Autumn Days": [
        ("PUMPKIN", "Orange gourd of the season"),
        ("HARVEST", "Gathering of ripe crops"),
        ("ACORN", "Nut of the oak tree"),
        ("SWEATER", "Warm knitted top"),
        ("FOLIAGE", "Leaves changing color"),
        ("SCARECROW", "Figure that guards a field"),
        ("HAYRIDE", "Ride on a wagon of hay"),
        ("CIDER", "Pressed apple drink"),
        ("MAPLE", "Tree with fiery fall leaves"),
        ("BONFIRE", "Large outdoor fire"),
        ("CHESTNUT", "Nut roasted in the fall"),
        ("CRISP", "Cool and fresh, like fall air"),
        ("ORCHARD", "Field of fruit trees"),
        ("RAKE", "Tool for gathering leaves"),
        ("CORNMAZE", "Puzzle cut into a field"),
        ("FLANNEL", "Soft warm fabric"),
        ("MIGRATE", "What birds do in autumn"),
        ("HARVESTMOON", "Full moon near the equinox"),
        ("SCARLET", "Bright fall red"),
        ("GOURD", "Hard-shelled autumn squash"),
    ],
    "Birds of a Feather": [
        ("SPARROW", "Small common brown bird"),
        ("PENGUIN", "Flightless bird of the cold"),
        ("FLAMINGO", "Pink bird that stands on one leg"),
        ("PELICAN", "Bird with a big throat pouch"),
        ("CARDINAL", "Bright red songbird"),
        ("OSTRICH", "Largest living bird"),
        ("PEACOCK", "Bird with a fanned tail"),
        ("WOODPECKER", "Bird that drills into trees"),
        ("SWALLOW", "Swift bird with forked tail"),
        ("VULTURE", "Bird that scavenges"),
        ("HUMMINGBIRD", "Tiny bird that hovers"),
        ("MAGPIE", "Black-and-white chattering bird"),
        ("PHEASANT", "Long-tailed game bird"),
        ("KINGFISHER", "Bird that dives for fish"),
        ("NIGHTINGALE", "Bird famed for its song"),
        ("CORMORANT", "Diving waterbird"),
        ("STARLING", "Bird that flocks in swarms"),
        ("BLUEJAY", "Noisy blue-crested bird"),
        ("FALCON", "Fast-diving bird of prey"),
        ("MOCKINGBIRD", "Bird that mimics others"),
    ],
    "Dinosaur Dig": [
        ("FOSSIL", "Preserved trace of ancient life"),
        ("RAPTOR", "Swift, clawed predator"),
        ("SKELETON", "Framework of bones"),
        ("HERBIVORE", "Plant-eating animal"),
        ("PREDATOR", "Animal that hunts others"),
        ("EXTINCT", "No longer existing"),
        ("TRICERATOPS", "Three-horned dinosaur"),
        ("PALEONTOLOGY", "Study of ancient life"),
        ("STEGOSAURUS", "Plated dinosaur with spikes"),
        ("AMBER", "Fossilized tree resin"),
        ("EXCAVATE", "Dig something out of the ground"),
        ("CARNIVORE", "Meat-eating animal"),
        ("VELOCIRAPTOR", "Small, fast hunting dinosaur"),
        ("SEDIMENT", "Layers of settled material"),
        ("PTERODACTYL", "Flying prehistoric reptile"),
        ("CRATER", "Pit left by an impact"),
        ("SPECIMEN", "Sample studied by scientists"),
        ("BEDROCK", "Solid rock beneath the soil"),
        ("PREHISTORIC", "From before written records"),
        ("DINOSAUR", "Ancient extinct reptile"),
    ],
    "Art Studio": [
        ("PALETTE", "Board for mixing paints"),
        ("CANVAS", "Cloth surface for painting"),
        ("SKETCH", "A rough drawing"),
        ("EASEL", "Stand that holds a canvas"),
        ("PIGMENT", "Substance that gives color"),
        ("PORTRAIT", "Painting of a person"),
        ("CHARCOAL", "Soft black drawing stick"),
        ("MURAL", "Painting on a wall"),
        ("BRUSH", "Tool for applying paint"),
        ("PASTEL", "Soft, chalky color stick"),
        ("GALLERY", "Place that displays art"),
        ("WATERCOLOR", "Paint thinned with water"),
        ("SCULPTURE", "A shaped three-dimensional work"),
        ("SHADING", "Adding depth with dark tones"),
        ("STILLLIFE", "Painting of arranged objects"),
        ("PALETTEKNIFE", "Blade for spreading paint"),
        ("PERSPECTIVE", "Depth shown on a flat surface"),
        ("COLLAGE", "Art made from pasted pieces"),
        ("VARNISH", "Clear protective coat"),
        ("MASTERPIECE", "An artist's finest work"),
    ],
    "The Toolbox": [
        ("HAMMER", "Tool for driving nails"),
        ("WRENCH", "Tool for turning bolts"),
        ("SCREWDRIVER", "Tool for turning screws"),
        ("PLIERS", "Tool for gripping"),
        ("CHISEL", "Blade for carving wood"),
        ("SANDPAPER", "Rough sheet for smoothing"),
        ("DRILL", "Tool that bores holes"),
        ("LEVEL", "Tool that checks for flatness"),
        ("TAPEMEASURE", "Tool for measuring length"),
        ("MALLET", "Soft-headed hammer"),
        ("CLAMP", "Device that holds pieces tight"),
        ("SOCKET", "Fitting that turns a bolt"),
        ("HACKSAW", "Saw for cutting metal"),
        ("PLANE", "Tool that shaves wood smooth"),
        ("TOOLBELT", "Strap for carrying tools"),
        ("RATCHET", "Tool that turns one way"),
        ("STAPLER", "Tool that fastens with staples"),
        ("CROWBAR", "Iron bar for prying"),
        ("WORKBENCH", "Sturdy table for projects"),
        ("SAWDUST", "Fine wood particles"),
    ],
    "Fairy Tale": [
        ("PRINCESS", "Royal daughter of a king"),
        ("DRAGON", "Fire-breathing beast"),
        ("CASTLE", "Fortified royal home"),
        ("WIZARD", "Wielder of magic"),
        ("GOBLIN", "Small mischievous creature"),
        ("ENCHANTED", "Placed under a spell"),
        ("KINGDOM", "Land ruled by a monarch"),
        ("GLASSSLIPPER", "Cinderella's lost shoe"),
        ("BEANSTALK", "Vine Jack climbed"),
        ("POTION", "Magical drink"),
        ("KNIGHT", "Armored warrior on a quest"),
        ("UNICORN", "Horse with a single horn"),
        ("MERMAID", "Half-fish, half-human creature"),
        ("SORCERESS", "Female worker of magic"),
        ("TREASURE", "Hidden riches"),
        ("BEAST", "Cursed creature of legend"),
        ("PUMPKIN", "Turned into a coach at midnight"),
        ("GODMOTHER", "Fairy who grants a wish"),
        ("SPINDLE", "Needle that pricks a princess"),
        ("HAPPILY", "How such tales end"),
    ],
    "Circus Acts": [
        ("ACROBAT", "Performer of daring flips"),
        ("TRAPEZE", "Swinging aerial bar"),
        ("JUGGLER", "One who tosses many objects"),
        ("RINGMASTER", "Host of the circus show"),
        ("TIGHTROPE", "Thin rope walked high up"),
        ("CLOWN", "Funny painted performer"),
        ("CANNON", "Launches a human performer"),
        ("UNICYCLE", "One-wheeled cycle"),
        ("STILTS", "Poles for walking tall"),
        ("CONTORTIONIST", "Performer who bends greatly"),
        ("BIGTOP", "The main circus tent"),
        ("MAGICIAN", "Performer of illusions"),
        ("ELEPHANT", "Large animal in the ring"),
        ("SPOTLIGHT", "Bright beam on a performer"),
        ("SEQUINS", "Sparkling costume discs"),
        ("SOMERSAULT", "A rolling flip"),
        ("TRAMPOLINE", "Springy jumping surface"),
        ("FIREEATER", "Performer who swallows flame"),
        ("SIDESHOW", "Small act beside the main event"),
        ("APPLAUSE", "Clapping for a performer"),
    ],
    "Coffee Shop": [
        ("ESPRESSO", "Strong concentrated coffee"),
        ("LATTE", "Espresso with steamed milk"),
        ("BARISTA", "One who makes coffee drinks"),
        ("CAPPUCCINO", "Espresso topped with foam"),
        ("CROISSANT", "Flaky buttery pastry"),
        ("MOCHA", "Coffee blended with chocolate"),
        ("MUFFIN", "Small domed baked cake"),
        ("BREW", "To make coffee"),
        ("STEAMER", "Wand that froths milk"),
        ("CARAMEL", "Sweet buttery flavor"),
        ("DECAF", "Coffee without caffeine"),
        ("SCONE", "Crumbly baked breakfast bread"),
        ("GRINDER", "Machine that crushes beans"),
        ("MACCHIATO", "Espresso marked with milk"),
        ("REFILL", "A second cupful"),
        ("BISCOTTI", "Twice-baked Italian cookie"),
        ("FROTH", "Foam atop a coffee"),
        ("SAUCER", "Small plate under a cup"),
        ("ROASTED", "How coffee beans are prepared"),
        ("APRON", "Worn to stay clean while serving"),
    ],
    "Bugs and Insects": [
        ("LADYBUG", "Small red spotted beetle"),
        ("BUTTERFLY", "Insect with bright wings"),
        ("GRASSHOPPER", "Jumping green insect"),
        ("DRAGONFLY", "Insect with long clear wings"),
        ("CATERPILLAR", "Larva that becomes a moth"),
        ("BEETLE", "Insect with hard wing cases"),
        ("CRICKET", "Chirping nighttime insect"),
        ("MOSQUITO", "Small biting insect"),
        ("FIREFLY", "Insect that glows at night"),
        ("TERMITE", "Wood-eating colony insect"),
        ("HORNET", "Large stinging wasp"),
        ("APHID", "Tiny sap-sucking pest"),
        ("MANTIS", "Insect that prays with its arms"),
        ("COCKROACH", "Hardy household pest"),
        ("CENTIPEDE", "Many-legged crawler"),
        ("HONEYBEE", "Insect that makes honey"),
        ("ANTHILL", "Mound built by ants"),
        ("COCOON", "Case a larva spins"),
        ("STINGER", "Sharp part that injects venom"),
        ("ANTENNA", "Feeler on an insect's head"),
    ],
    "Mountain Peaks": [
        ("SUMMIT", "The very top of a mountain"),
        ("GLACIER", "Slow-moving river of ice"),
        ("AVALANCHE", "Sudden slide of snow"),
        ("BOULDER", "Very large rock"),
        ("CREVASSE", "Deep crack in a glacier"),
        ("ALTITUDE", "Height above sea level"),
        ("RIDGE", "Long narrow crest of land"),
        ("PLATEAU", "High flat stretch of land"),
        ("CLIMBER", "One who scales heights"),
        ("CANYON", "Deep river-cut valley"),
        ("SNOWCAP", "Snow at a peak's top"),
        ("VALLEY", "Low land between hills"),
        ("FOOTHILL", "Low hill at a mountain's base"),
        ("TIMBERLINE", "Where trees stop growing"),
        ("SLOPE", "A mountain's inclined side"),
        ("CLIFF", "Steep rock face"),
        ("ALPINE", "Of the high mountains"),
        ("EXPEDITION", "An organized climbing trip"),
        ("BASECAMP", "Starting camp for a climb"),
        ("PERMAFROST", "Ground that stays frozen"),
    ],
    "Pizza Party": [
        ("PEPPERONI", "Spicy sliced sausage topping"),
        ("MOZZARELLA", "Classic stretchy pizza cheese"),
        ("CRUST", "Baked outer edge of a pizza"),
        ("OREGANO", "Herb sprinkled on pizza"),
        ("TOPPINGS", "Items placed on a pizza"),
        ("MARINARA", "Tomato-based sauce"),
        ("PEPPERS", "Sliced vegetable topping"),
        ("MUSHROOM", "Fungus used as a topping"),
        ("DELIVERY", "Bringing food to your door"),
        ("PEPPERFLAKE", "Spicy red seasoning"),
        ("SLICE", "A single wedge of pizza"),
        ("DOUGH", "Uncooked base of a pizza"),
        ("PARMESAN", "Hard grated cheese"),
        ("PIZZERIA", "Shop that sells pizza"),
        ("BASIL", "Fragrant green herb"),
        ("PINEAPPLE", "Debated sweet topping"),
        ("OVEN", "Where pizza bakes"),
        ("CALZONE", "Folded stuffed pizza"),
        ("ANCHOVY", "Small salty fish topping"),
        ("PIZZACUTTER", "Wheeled slicing tool"),
    ],
    "Sports Arena": [
        ("STADIUM", "Large venue for games"),
        ("REFEREE", "Official who calls the game"),
        ("JERSEY", "Shirt worn by a player"),
        ("BLEACHERS", "Tiered seats for fans"),
        ("HALFTIME", "Break in the middle of a game"),
        ("TROPHY", "Prize for the winner"),
        ("MASCOT", "Costumed team symbol"),
        ("SCOREBOARD", "Display of the game's score"),
        ("OVERTIME", "Extra play to break a tie"),
        ("STADIUMLIGHTS", "Bright lamps over the field"),
        ("DEFENSE", "Side trying to stop scoring"),
        ("OFFENSE", "Side trying to score"),
        ("WHISTLE", "Sound that stops play"),
        ("CHAMPION", "The top competitor"),
        ("PENALTY", "Punishment for breaking a rule"),
        ("TIMEOUT", "A short pause in play"),
        ("TAILGATE", "Party in a stadium lot"),
        ("STANDINGS", "Ranking of the teams"),
        ("VICTORY", "A win"),
        ("TOURNAMENT", "A series of matches"),
    ],
    "Board Games": [
        ("CHECKERS", "Game of red and black discs"),
        ("DOMINO", "Tile marked with dots"),
        ("DICE", "Cubes rolled for a number"),
        ("STRATEGY", "A plan to win"),
        ("PAWN", "Lowest chess piece"),
        ("SHUFFLE", "Mix up the cards"),
        ("TOKEN", "Piece that marks a player"),
        ("CHECKMATE", "The winning chess move"),
        ("SPINNER", "Arrow spun to move"),
        ("BACKGAMMON", "Ancient game of points and pips"),
        ("MEEPLE", "Wooden player figure"),
        ("SCRABBLE", "Game of building words"),
        ("OPPONENT", "The player against you"),
        ("ROULETTE", "Wheel of chance"),
        ("BISHOP", "Chess piece moving diagonally"),
        ("TURN", "A player's chance to move"),
        ("GAMEBOARD", "Surface where play happens"),
        ("SOLITAIRE", "Game for one player"),
        ("DEALER", "One who hands out cards"),
        ("VICTORY", "A win"),
    ],
    "The Library": [
        ("NOVEL", "A long work of fiction"),
        ("SHELVES", "Rows that hold books"),
        ("LIBRARIAN", "Keeper of a library"),
        ("CATALOG", "List of a library's holdings"),
        ("CHAPTER", "A division of a book"),
        ("BOOKMARK", "Marker that saves your place"),
        ("REFERENCE", "Section for looking things up"),
        ("BORROW", "Take out on loan"),
        ("SILENCE", "Expected quiet of the room"),
        ("PAPERBACK", "Book with a soft cover"),
        ("BIOGRAPHY", "Story of a person's life"),
        ("OVERDUE", "Returned past the date"),
        ("ENCYCLOPEDIA", "Reference of many topics"),
        ("FICTION", "Made-up stories"),
        ("HARDCOVER", "Book with a stiff cover"),
        ("ATLAS", "Book of maps"),
        ("READING", "Taking in written words"),
        ("ARCHIVE", "Store of old documents"),
        ("PERIODICAL", "Magazine or journal"),
        ("MANUSCRIPT", "An author's original text"),
    ],
    "Rainforest": [
        ("CANOPY", "Leafy roof of the forest"),
        ("HUMID", "Warm and very damp"),
        ("ORCHID", "Exotic tropical flower"),
        ("SLOTH", "Slow tree-dwelling animal"),
        ("FROG", "Small amphibian of the trees"),
        ("BIODIVERSITY", "Variety of living things"),
        ("UNDERSTORY", "Shaded layer below the canopy"),
        ("MACAW", "Large colorful parrot"),
        ("VINE", "Climbing woody plant"),
        ("TROPICAL", "Of the warm wet zones"),
        ("FERN", "Feathery leafy plant"),
        ("RAINFALL", "Amount of rain that drops"),
        ("JAGUAR", "Powerful spotted cat"),
        ("EMERGENT", "Tallest trees above the rest"),
        ("MOSS", "Soft green forest carpet"),
        ("TOUCAN", "Bird with a huge bill"),
        ("ECOSYSTEM", "A community of living things"),
        ("DECOMPOSE", "Break down into soil"),
        ("CHAMELEON", "Lizard that changes color"),
        ("MONSOON", "Season of heavy rain"),
    ],
    "Frozen Treats": [
        ("ICECREAM", "Frozen churned dessert"),
        ("SORBET", "Fruity frozen ice"),
        ("POPSICLE", "Frozen treat on a stick"),
        ("SUNDAE", "Ice cream with toppings"),
        ("GELATO", "Dense Italian ice cream"),
        ("SPRINKLES", "Tiny colorful toppings"),
        ("MILKSHAKE", "Blended cold drink"),
        ("SHERBET", "Light fruity frozen dessert"),
        ("WAFFLECONE", "Crisp holder for a scoop"),
        ("SLUSHIE", "Icy flavored drink"),
        ("CHOCOLATE", "Popular sweet flavor"),
        ("VANILLA", "Classic pale flavor"),
        ("SCOOP", "A rounded ball of ice cream"),
        ("FROYO", "Tangy frozen yogurt"),
        ("SNOWCONE", "Shaved ice with syrup"),
        ("BANANA", "Split under ice cream"),
        ("CHERRY", "Topping placed on top"),
        ("CARAMEL", "Sweet buttery drizzle"),
        ("FUDGE", "Rich chocolate topping"),
        ("PARFAIT", "Layered chilled dessert"),
    ],
    "Grand Castle": [
        ("DRAWBRIDGE", "Bridge that lifts over a moat"),
        ("TURRET", "Small tower on a castle"),
        ("MOAT", "Water ring around a castle"),
        ("THRONE", "Seat of a king or queen"),
        ("DUNGEON", "Dark underground prison"),
        ("RAMPART", "Defensive castle wall"),
        ("PORTCULLIS", "Heavy iron castle gate"),
        ("BANNER", "Flag bearing a crest"),
        ("BATTLEMENT", "Notched top of a wall"),
        ("COURTYARD", "Open space within walls"),
        ("KNIGHT", "Armored castle warrior"),
        ("CHAMBER", "A private room"),
        ("GATEHOUSE", "Guarded castle entrance"),
        ("TAPESTRY", "Woven wall hanging"),
        ("KEEP", "Strong central tower"),
        ("HERALD", "Announcer at court"),
        ("CATAPULT", "Machine that hurls stones"),
        ("CHANDELIER", "Hanging light of candles"),
        ("FORTRESS", "A strongly defended place"),
        ("DRAWBAR", "Bar that bolts a gate"),
    ],
    "Getting Dressed": [
        ("SWEATER", "Warm knitted top"),
        ("TROUSERS", "Garment for the legs"),
        ("JACKET", "Short coat"),
        ("SNEAKERS", "Casual sport shoes"),
        ("BUTTONS", "Fasteners on a shirt"),
        ("SCARF", "Cloth worn at the neck"),
        ("GLOVES", "Coverings for the hands"),
        ("POCKET", "Small pouch in clothing"),
        ("BLOUSE", "Loose woman's shirt"),
        ("SANDALS", "Open summer footwear"),
        ("NECKTIE", "Strip knotted at the collar"),
        ("OVERCOAT", "Long warm outer coat"),
        ("WARDROBE", "One's set of clothes"),
        ("SLIPPERS", "Soft indoor shoes"),
        ("CARDIGAN", "Buttoned knitted sweater"),
        ("BELT", "Strap around the waist"),
        ("RAINCOAT", "Coat that keeps you dry"),
        ("STOCKING", "Long covering for the leg"),
        ("HOODIE", "Sweatshirt with a hood"),
        ("ZIPPER", "Sliding clothing fastener"),
    ],
    "Colors and Shades": [
        ("CRIMSON", "Deep rich red"),
        ("TURQUOISE", "Blue-green like the gem"),
        ("MAGENTA", "Bright purplish pink"),
        ("EMERALD", "Vivid green like the jewel"),
        ("LAVENDER", "Pale soft purple"),
        ("SCARLET", "Bright vivid red"),
        ("INDIGO", "Deep blue-violet"),
        ("MAROON", "Dark brownish red"),
        ("AMBER", "Warm golden orange"),
        ("VIOLET", "A purple hue"),
        ("BEIGE", "Pale sandy tan"),
        ("CHARCOAL", "Very dark gray"),
        ("CORAL", "Pinkish orange"),
        ("IVORY", "Creamy off-white"),
        ("OLIVE", "Dull yellowish green"),
        ("TEAL", "Deep blue-green"),
        ("MAUVE", "Grayish purple"),
        ("SAPPHIRE", "Deep blue like the gem"),
        ("BRONZE", "Brownish metallic tone"),
        ("PERIWINKLE", "Pale blue-lavender"),
    ],
    "Pirate Voyage": [
        ("TREASURE", "Buried riches"),
        ("CUTLASS", "Curved pirate sword"),
        ("PARROT", "Bird perched on a shoulder"),
        ("PLANK", "Board a captive walks"),
        ("ANCHOR", "Holds a ship in place"),
        ("COMPASS", "Tool that points north"),
        ("GALLEON", "Large sailing ship"),
        ("EYEPATCH", "Cover over one eye"),
        ("SPYGLASS", "Handheld telescope"),
        ("MUTINY", "Revolt against the captain"),
        ("DOUBLOON", "Old gold coin"),
        ("CAPTAIN", "Leader of the ship"),
        ("CANNON", "Ship's heavy gun"),
        ("SCURVY", "Sailor's vitamin illness"),
        ("MAROONED", "Stranded on an island"),
        ("SCHOONER", "Fast two-masted ship"),
        ("BOOTY", "A pirate's stolen loot"),
        ("STARBOARD", "The ship's right side"),
        ("CROWSNEST", "Lookout high on a mast"),
        ("BUCCANEER", "A Caribbean pirate"),
    ],
    "Trains and Rails": [
        ("LOCOMOTIVE", "Engine that pulls a train"),
        ("CABOOSE", "Last car of a train"),
        ("STATION", "Where trains stop for riders"),
        ("CONDUCTOR", "One who runs the train"),
        ("PLATFORM", "Where you board a train"),
        ("BOXCAR", "Enclosed freight car"),
        ("RAILWAY", "Track system for trains"),
        ("WHISTLE", "Signal blown by a train"),
        ("TUNNEL", "Passage through a hill"),
        ("SLEEPER", "Car with beds for the night"),
        ("FREIGHT", "Cargo carried by train"),
        ("TRESTLE", "Bridge that carries rails"),
        ("JUNCTION", "Where two lines meet"),
        ("TIMETABLE", "Schedule of train times"),
        ("EXPRESS", "A fast, few-stop train"),
        ("COUPLING", "Link between two cars"),
        ("SIGNAL", "Light that guides trains"),
        ("LOCOMOTION", "Movement from place to place"),
        ("STEAMENGINE", "Old coal-fired locomotive"),
        ("TERMINAL", "End station of a line"),
    ],
    "The Bakery": [
        ("BAGUETTE", "Long crusty French loaf"),
        ("CROISSANT", "Flaky buttery pastry"),
        ("CUPCAKE", "Small frosted cake"),
        ("SOURDOUGH", "Tangy naturally leavened bread"),
        ("PRETZEL", "Salty twisted baked snack"),
        ("FROSTING", "Sweet coating on a cake"),
        ("KNEAD", "Work dough with the hands"),
        ("DANISH", "Sweet layered pastry"),
        ("YEAST", "Microbe that makes dough rise"),
        ("MUFFIN", "Small domed baked cake"),
        ("ROLLINGPIN", "Cylinder for flattening dough"),
        ("CINNAMON", "Warm spice for rolls"),
        ("ECLAIR", "Cream-filled iced pastry"),
        ("BRIOCHE", "Rich buttery egg bread"),
        ("OVENMITT", "Glove for handling hot pans"),
        ("TURNOVER", "Folded fruit pastry"),
        ("DOUGHNUT", "Ring-shaped fried treat"),
        ("MERINGUE", "Whipped baked egg whites"),
        ("SPRINKLES", "Tiny colorful toppings"),
        ("CROUTON", "Small crisp bread cube"),
    ],
    "Gemstones": [
        ("DIAMOND", "Hardest and clearest gem"),
        ("EMERALD", "Vivid green gem"),
        ("SAPPHIRE", "Deep blue gem"),
        ("RUBY", "Precious red gem"),
        ("AMETHYST", "Purple quartz gem"),
        ("TOPAZ", "Golden or blue gem"),
        ("OPAL", "Gem with shifting colors"),
        ("GARNET", "Deep red gemstone"),
        ("TURQUOISE", "Blue-green stone"),
        ("PERIDOT", "Olive-green gem"),
        ("AQUAMARINE", "Pale sea-blue gem"),
        ("ONYX", "Black banded stone"),
        ("JADE", "Green stone prized in Asia"),
        ("MOONSTONE", "Gem with a milky glow"),
        ("CARAT", "Unit of a gem's weight"),
        ("FACET", "Cut flat face of a gem"),
        ("QUARTZ", "Common crystal mineral"),
        ("CITRINE", "Yellow quartz gem"),
        ("PEARL", "Gem formed in an oyster"),
        ("GEODE", "Rock lined with crystals"),
    ],
    "Freshwater Pond": [
        ("LILYPAD", "Floating leaf on a pond"),
        ("TADPOLE", "Young frog with a tail"),
        ("DRAGONFLY", "Insect with clear wings"),
        ("CATTAIL", "Tall reed by the water"),
        ("MINNOW", "Small pond fish"),
        ("RIPPLE", "Small wave on the surface"),
        ("NEWT", "Small water salamander"),
        ("DUCKWEED", "Tiny floating green plant"),
        ("HERON", "Long-legged wading bird"),
        ("SNAIL", "Slow shelled crawler"),
        ("BULLFROG", "Large deep-voiced frog"),
        ("REEDS", "Tall grasses at the edge"),
        ("TURTLE", "Shelled pond reptile"),
        ("ALGAE", "Green film on the water"),
        ("BEAVER", "Dam-building rodent"),
        ("MALLARD", "Common green-headed duck"),
        ("DAMSELFLY", "Slender pondside insect"),
        ("MUDDY", "Full of wet soil"),
        ("SHALLOW", "Not deep"),
        ("MARSH", "Soft wet grassy land"),
    ],
    "Bedtime": [
        ("PILLOW", "Soft cushion for the head"),
        ("BLANKET", "Cover that keeps you warm"),
        ("PAJAMAS", "Clothes worn to bed"),
        ("NIGHTLIGHT", "Small lamp for the dark"),
        ("LULLABY", "Soft song to bring sleep"),
        ("MATTRESS", "Padded base of a bed"),
        ("DREAM", "Story the mind tells in sleep"),
        ("YAWN", "Wide open-mouthed breath"),
        ("SLIPPERS", "Soft shoes for indoors"),
        ("BEDTIMESTORY", "Tale read before sleep"),
        ("MOONLIGHT", "Soft glow of the moon"),
        ("SNORE", "Rough sound of deep sleep"),
        ("QUILT", "Padded stitched bedcover"),
        ("DROWSY", "Feeling sleepy"),
        ("NAP", "A short sleep"),
        ("TUCKIN", "Settle someone into bed"),
        ("ALARMCLOCK", "Device that wakes you"),
        ("COZY", "Warm and snug"),
        ("TEDDYBEAR", "Stuffed toy for comfort"),
        ("MIDNIGHT", "Twelve at night"),
    ],
    "The Airport": [
        ("RUNWAY", "Strip where planes take off"),
        ("BOARDING", "Getting on the plane"),
        ("TERMINAL", "Building where flights depart"),
        ("LUGGAGE", "Bags you travel with"),
        ("PASSPORT", "Document for travel abroad"),
        ("SECURITY", "Screening before the gate"),
        ("COCKPIT", "Where the pilots sit"),
        ("TAKEOFF", "When a plane leaves the ground"),
        ("SUITCASE", "Case for packing clothes"),
        ("LAYOVER", "Wait between flights"),
        ("BAGGAGE", "Traveler's bags"),
        ("ARRIVAL", "A flight coming in"),
        ("DEPARTURE", "A flight going out"),
        ("PILOT", "One who flies the plane"),
        ("TICKET", "Pass to board a flight"),
        ("CUSTOMS", "Border check for goods"),
        ("JETWAY", "Bridge to the plane door"),
        ("TURBULENCE", "Bumpy air in flight"),
        ("CAROUSEL", "Belt where bags arrive"),
        ("CONTROLTOWER", "Where flights are directed"),
    ],
    "Spring Blooms": [
        ("TULIP", "Cup-shaped spring flower"),
        ("DAFFODIL", "Yellow trumpet flower"),
        ("BLOSSOM", "A flower in bloom"),
        ("BUTTERFLY", "Insect with bright wings"),
        ("SPROUT", "Young shoot from a seed"),
        ("POLLEN", "Yellow dust from flowers"),
        ("RAINDROP", "A single drop of rain"),
        ("MEADOW", "Grassy open field"),
        ("CROCUS", "Early spring bloom"),
        ("NECTAR", "Sweet flower liquid"),
        ("GREENERY", "Fresh green plants"),
        ("BUMBLEBEE", "Fuzzy pollinator"),
        ("BUDDING", "Just starting to bloom"),
        ("HYACINTH", "Fragrant spring flower"),
        ("SUNSHINE", "Bright light from the sun"),
        ("PUDDLE", "Small pool of rainwater"),
        ("ROBIN", "Bird of early spring"),
        ("GARDEN", "Where flowers are grown"),
        ("BREEZE", "Gentle spring wind"),
        ("PRIMROSE", "Low early-blooming flower"),
    ],
    "Woodland Creatures": [
        ("SQUIRREL", "Bushy-tailed nut gatherer"),
        ("HEDGEHOG", "Small spiny animal"),
        ("BADGER", "Burrowing striped mammal"),
        ("CHIPMUNK", "Small striped rodent"),
        ("RACCOON", "Masked nighttime forager"),
        ("PORCUPINE", "Animal with sharp quills"),
        ("WEASEL", "Slender quick predator"),
        ("FOXGLOVE", "Tall bell-shaped flower"),
        ("BEAVER", "Dam-building rodent"),
        ("OWL", "Nighttime bird of the woods"),
        ("DEER", "Graceful antlered animal"),
        ("SKUNK", "Animal with a strong spray"),
        ("MUSHROOM", "Fungus of the forest floor"),
        ("BURROW", "Animal's underground home"),
        ("OTTER", "Playful river swimmer"),
        ("ACORN", "Nut of the oak"),
        ("MOLE", "Blind underground digger"),
        ("THICKET", "Dense growth of shrubs"),
        ("WOODPECKER", "Bird that drills trees"),
        ("FAWN", "A baby deer"),
    ],
    "Card Games": [
        ("SHUFFLE", "Mix up the deck"),
        ("DEALER", "One who hands out cards"),
        ("BLUFF", "Pretend to hold a strong hand"),
        ("TRUMP", "The winning suit"),
        ("JOKER", "The wild extra card"),
        ("SOLITAIRE", "Game played alone"),
        ("POKER", "Betting game of hands"),
        ("DIAMONDS", "A red card suit"),
        ("DISCARD", "Throw away a card"),
        ("JACKPOT", "The big pot of winnings"),
        ("WILDCARD", "Card that stands for any"),
        ("SPADES", "A black card suit"),
        ("DEALCARDS", "Hand cards to players"),
        ("RUMMY", "Game of matching sets"),
        ("SHOWDOWN", "When hands are revealed"),
        ("HEARTS", "A red card suit"),
        ("FACECARD", "King, queen, or jack"),
        ("CLUBS", "A black card suit"),
        ("BRIDGE", "Game of bidding and tricks"),
        ("ANTE", "Bet made before the deal"),
    ],
    "Ancient Egypt": [
        ("PHARAOH", "Ancient Egyptian ruler"),
        ("PYRAMID", "Great royal tomb"),
        ("SPHINX", "Lion-bodied statue"),
        ("MUMMY", "Preserved wrapped body"),
        ("HIEROGLYPH", "Picture-based writing"),
        ("PAPYRUS", "Reed used for paper"),
        ("SCARAB", "Sacred beetle symbol"),
        ("OBELISK", "Tall four-sided pillar"),
        ("PHARAOHS", "Line of Egyptian kings"),
        ("SARCOPHAGUS", "Stone coffin"),
        ("NILE", "Great river of Egypt"),
        ("TOMB", "Burial chamber"),
        ("PAPUS", "Reed boat of the river"),
        ("PYRAMIDION", "Capstone of a pyramid"),
        ("AMULET", "Charm worn for protection"),
        ("DYNASTY", "A line of rulers"),
        ("PAPYRI", "Ancient scrolls"),
        ("PHARAONIC", "Of the pharaohs"),
        ("EMBALM", "Preserve a body"),
        ("CARTOUCHE", "Oval framing a royal name"),
    ],
    "Volcano and Rock": [
        ("MAGMA", "Molten rock underground"),
        ("LAVA", "Molten rock at the surface"),
        ("ERUPTION", "A volcanic outburst"),
        ("CRATER", "Bowl at a volcano's top"),
        ("BASALT", "Dark volcanic rock"),
        ("GRANITE", "Hard speckled rock"),
        ("PUMICE", "Light frothy volcanic rock"),
        ("MINERAL", "Natural solid substance"),
        ("SEDIMENT", "Settled layers of matter"),
        ("GEYSER", "Jet of hot spring water"),
        ("QUARTZ", "Common crystal mineral"),
        ("BEDROCK", "Solid rock below the soil"),
        ("LIMESTONE", "Rock made of shells"),
        ("VOLCANO", "Mountain that erupts"),
        ("OBSIDIAN", "Glassy volcanic rock"),
        ("TREMOR", "A small earthquake"),
        ("MARBLE", "Polished metamorphic rock"),
        ("ASHCLOUD", "Dust thrown by an eruption"),
        ("SANDSTONE", "Rock of pressed sand"),
        ("FAULTLINE", "Crack where quakes occur"),
    ],
    "Feelings": [
        ("JOYFUL", "Full of happiness"),
        ("NERVOUS", "Anxious and uneasy"),
        ("GRATEFUL", "Thankful for something"),
        ("CURIOUS", "Eager to learn"),
        ("LONELY", "Sad from being alone"),
        ("EXCITED", "Thrilled and eager"),
        ("PROUD", "Pleased with an achievement"),
        ("CONTENT", "Calmly satisfied"),
        ("JEALOUS", "Envious of another"),
        ("HOPEFUL", "Looking forward with hope"),
        ("ANXIOUS", "Worried about what's ahead"),
        ("CHEERFUL", "Bright and happy"),
        ("EMBARRASSED", "Feeling awkward or ashamed"),
        ("PEACEFUL", "Calm and untroubled"),
        ("FRUSTRATED", "Upset by an obstacle"),
        ("SURPRISED", "Caught off guard"),
        ("CONFIDENT", "Sure of oneself"),
        ("GRUMPY", "In a bad mood"),
        ("RELIEVED", "Freed from worry"),
        ("BASHFUL", "Shy and timid"),
    ],
    "Post Office": [
        ("ENVELOPE", "Paper cover for a letter"),
        ("STAMP", "Sticker that pays postage"),
        ("PARCEL", "A wrapped package"),
        ("MAILBOX", "Box that holds letters"),
        ("POSTCARD", "Card mailed without an envelope"),
        ("DELIVERY", "Bringing mail to you"),
        ("ZIPCODE", "Number that routes mail"),
        ("POSTAGE", "Fee to send mail"),
        ("COURIER", "One who carries messages"),
        ("RETURNADDRESS", "Sender's address on mail"),
        ("PACKAGE", "A boxed item to send"),
        ("SORTING", "Ordering mail by route"),
        ("REGISTERED", "Tracked, secured mail"),
        ("FORWARDING", "Sending mail to a new place"),
        ("POSTMARK", "Ink stamp with the date"),
        ("CARRIER", "One who delivers the mail"),
        ("PARCELPOST", "Service for shipping packages"),
        ("AIRMAIL", "Mail carried by plane"),
        ("SEALED", "Closed tightly shut"),
        ("RECIPIENT", "One who receives the mail"),
    ],
    "Halloween Night": [
        ("PUMPKIN", "Orange gourd carved for the night"),
        ("COSTUME", "Outfit worn to disguise"),
        ("SKELETON", "Framework of bones"),
        ("CAULDRON", "Witch's large boiling pot"),
        ("SPIDERWEB", "Sticky trap spun by a spider"),
        ("HAUNTED", "Visited by ghosts"),
        ("GOBLIN", "Small mischievous creature"),
        ("LANTERN", "Carved glowing pumpkin"),
        ("WITCH", "Caster of spells on a broom"),
        ("SPOOKY", "Eerie and frightening"),
        ("CANDY", "Sweet treat given out"),
        ("COBWEB", "Old dusty spider silk"),
        ("VAMPIRE", "Fanged creature of the night"),
        ("MIDNIGHT", "Twelve at night"),
        ("SCARECROW", "Straw figure in a field"),
        ("MONSTER", "A frightening creature"),
        ("BROOMSTICK", "A witch's flying ride"),
        ("SHADOW", "Dark shape cast by light"),
        ("TREATBAG", "Sack for collected candy"),
        ("CEMETERY", "Where the dead are buried"),
    ],
}
