"""Curated word/clue banks for the daily word search and crossword.

Deliberately not tied to current events: these are evergreen, whimsical
themes so the games hold up regardless of the news cycle. Words are
uppercase, letters only (no spaces or hyphens) so they place cleanly on a
grid. Clues are only used by the crossword; the word search just needs the
word list.

Add a new theme by adding a new (word, clue) list below. Keep clues short
(under ~45 chars looks best in the sidebar clue list) and avoid duplicate
words within a theme.
"""

THEMES = {
    "Ocean Life": [
        ("WHALE", "Largest animal on Earth"),
        ("CORAL", "Reef-building sea organism"),
        ("OCTOPUS", "Eight-armed cephalopod"),
        ("STARFISH", "Sea animal shaped like a star"),
        ("SHARK", "Cartilaginous ocean predator"),
        ("DOLPHIN", "Playful, clever marine mammal"),
        ("PLANKTON", "Tiny drifting sea organisms"),
        ("TIDE", "Daily rise and fall of the sea"),
        ("KELP", "Large brown seaweed"),
        ("ANCHOR", "Keeps a ship from drifting"),
        ("LAGOON", "Shallow water near a coast"),
        ("CRAB", "Walks sideways, has claws"),
        ("PEARL", "Gem formed inside an oyster"),
        ("REEF", "Coral ridge near the surface"),
        ("HARBOR", "Sheltered place for ships"),
        ("SEAHORSE", "Fish with a horse-shaped head"),
        ("JELLYFISH", "Gelatinous, stings"),
        ("TSUNAMI", "Huge wave from a quake"),
        ("LOBSTER", "Clawed crustacean, turns red cooked"),
        ("CURRENT", "Steady flow of moving water"),
    ],
    "Space Explorer": [
        ("ROCKET", "Vehicle that launches into orbit"),
        ("COMET", "Icy body with a glowing tail"),
        ("GALAXY", "Huge collection of star systems"),
        ("METEOR", "Shooting star burning in the sky"),
        ("ORBIT", "Path a planet takes around a star"),
        ("NEBULA", "Cloud of gas and dust in space"),
        ("ASTEROID", "Rocky object orbiting the sun"),
        ("TELESCOPE", "Tool for viewing distant stars"),
        ("ASTRONAUT", "Person trained to travel in space"),
        ("SATELLITE", "Object orbiting a planet"),
        ("GRAVITY", "Force that pulls objects together"),
        ("ECLIPSE", "One body blocks light from another"),
        ("MOON", "Earth's only natural satellite"),
        ("SATURN", "Planet known for its rings"),
        ("MARS", "The red planet"),
        ("STARLIGHT", "Light that traveled years to reach us"),
        ("CAPSULE", "Crew compartment of a spacecraft"),
        ("LAUNCHPAD", "Where a rocket lifts off"),
        ("COSMOS", "The universe as an orderly whole"),
        ("CONSTELLATION", "Named pattern of stars"),
    ],
    "Kitchen Table": [
        ("SKILLET", "Flat-bottomed pan for frying"),
        ("WHISK", "Tool for beating eggs or batter"),
        ("SIMMER", "Cook gently just below boiling"),
        ("PANTRY", "Small room for storing food"),
        ("RECIPE", "Instructions for making a dish"),
        ("SPATULA", "Flat tool for flipping food"),
        ("KETTLE", "Container for boiling water"),
        ("GARLIC", "Pungent bulb used in cooking"),
        ("CINNAMON", "Warm, sweet spice from bark"),
        ("CASSEROLE", "Baked dish made in one pan"),
        ("BLENDER", "Appliance that purees or mixes"),
        ("APPETIZER", "Small dish served before the meal"),
        ("MARINATE", "Soak food in seasoned liquid"),
        ("COLANDER", "Bowl with holes for draining"),
        ("DESSERT", "Sweet course at the end of a meal"),
        ("OMELET", "Folded dish made of beaten eggs"),
        ("PRETZEL", "Salty, twisted baked snack"),
        ("VINEGAR", "Sour liquid used in dressings"),
        ("TEASPOON", "Small unit for measuring spice"),
        ("BAKERY", "Shop that sells fresh bread"),
    ],
    "Backyard Camping": [
        ("TENT", "Portable shelter for sleeping outside"),
        ("LANTERN", "Portable light for a campsite"),
        ("CAMPFIRE", "Fire built for warmth outdoors"),
        ("MARSHMALLOW", "Sweet treat roasted on a stick"),
        ("SLEEPBAG", "Padded sack for outdoor sleeping"),
        ("COMPASS", "Tool that points north"),
        ("FLASHLIGHT", "Handheld electric light"),
        ("HAMMOCK", "Hanging bed for lounging outside"),
        ("TRAIL", "Path used for hiking"),
        ("BACKPACK", "Bag carried on the shoulders"),
        ("FIREFLY", "Bug that glows at night"),
        ("BINOCULARS", "Tool for seeing far away"),
        ("CANOE", "Narrow boat paddled by hand"),
        ("BONFIRE", "Large outdoor fire"),
        ("STARGAZING", "Looking up at the night sky"),
        ("COOLER", "Box that keeps food and drinks cold"),
        ("RIVERBANK", "Land along the edge of a river"),
        ("WHISTLE", "Small tool that makes a sharp sound"),
        ("PINECONE", "Woody seed case from a conifer"),
        ("MOSQUITO", "Small biting insect"),
    ],
    "Movie Night": [
        ("POPCORN", "Snack popped from kernels"),
        ("SEQUEL", "Follow-up to an earlier film"),
        ("DIRECTOR", "Person who oversees a film's making"),
        ("SUBTITLE", "Translated text at the bottom of a screen"),
        ("PREMIERE", "A film's first public showing"),
        ("SOUNDTRACK", "Music that plays through a film"),
        ("CAMEO", "Brief appearance by a known actor"),
        ("SCREENPLAY", "Written script for a film"),
        ("BLOCKBUSTER", "Hugely successful film"),
        ("ANIMATION", "Film made from drawn or CGI frames"),
        ("TRAILER", "Short preview of a coming film"),
        ("PLOT", "The story of a film"),
        ("VILLAIN", "The bad guy in the story"),
        ("COSTUME", "Clothing worn by a character"),
        ("STUDIO", "Company that produces films"),
        ("REWIND", "Go back to an earlier scene"),
        ("MATINEE", "Afternoon showing of a film"),
        ("CREDITS", "Names listed at a film's end"),
        ("SCENE", "A single continuous piece of action"),
        ("BOXOFFICE", "Measure of a film's ticket sales"),
    ],
    "Road Trip": [
        ("HIGHWAY", "Major road between cities"),
        ("SUITCASE", "Case for packing clothes"),
        ("MAP", "Guide showing roads and routes"),
        ("DINER", "Casual roadside restaurant"),
        ("GASSTOP", "Quick stop to refuel"),
        ("BILLBOARD", "Large roadside advertisement"),
        ("PASSENGER", "Rider who isn't driving"),
        ("DETOUR", "Route that avoids the usual path"),
        ("LICENSE", "Permit required to drive"),
        ("TRUNK", "Storage space at the back of a car"),
        ("SPEEDOMETER", "Gauge showing how fast you're going"),
        ("MOTEL", "Roadside lodging for travelers"),
        ("TOLLBOOTH", "Stop for paying to use a road"),
        ("SOUVENIR", "Item kept to remember a trip"),
        ("CARAVAN", "Group of vehicles traveling together"),
        ("MILEAGE", "Distance a vehicle has traveled"),
        ("PITSTOP", "Short break during a long drive"),
        ("SUNROOF", "Panel that opens in a car's roof"),
        ("HORIZON", "Line where the sky meets the land"),
        ("GLOVEBOX", "Small storage compartment in a car"),
    ],
}
